---
title: "What are the main health concerns of Men who have Sex with Men (MSM) in French-speaking Belgium? Results from a syndemic-informed Delphi study with peer volunteers from LGBTQIA organisations"
format: docx
---

```{r import_data}
#| include: false
source("./scripts/import_data.R", encoding = "UTF-8")
source("./scripts/prepare_demog_data.R", encoding = "UTF-8")
source("./scripts/wave2_analysis.R", encoding = "UTF-8")
```

**Background:**  A syndemic consists of interacting epidemics producing an excess burden in a disadvantaged population. The theory has been applied to the health of MSM since 2003 but the field lacks consensus on which conditions constitute a syndemic. Furthermore, transgender MSM are nearly always omitted from syndemic research. In order to develop a research project tailored to the needs of all MSM in French-speaking Belgium, we conducted a Delphi study to explore their main health concerns.
\
**Methods:** In September 2022, we recruited cisgender and transgender members from LGBTQIA organisations in French-speaking Belgium. Experts were selected based on their lived experience and expertise in community-led organisations. The Delphi study consisted of three rounds designed to (1) elicit ideas on psychological, social and physical issues and their interactions; (2) select the most relevant issues and; (3) rank them by importance.
\
**Results:** `r .N_cis` cisgender experts and `r .N_trans` transgender experts participated in the study. During the second round, cisgender and transgender experts scored `r ncol(wave2_data_cis)` and `r ncol(wave2_data_trans)` items respectively on a five-item Likert scale. Using a consensus threshold of ≥ 80% experts rating ≥ 4, `r length(variable_cisgender[["80%"]])` issues were selected by cisgender experts: low self-esteem, loneliness, low social support, sexual risk behaviours, chemsex, intra-community hypersexualisation, and patriarchal pressures on masculinity. Using the same criterion, transgender experts selected `r length(variable_transgender[["80%"]])` variables: anxiety, suicidality, loneliness, low social support, deprivation, transphobia, poor healthcare access, identity denial, as well as lack of knowledge on transness. Of note, 100% of cisgender experts agreed on sexual risk behaviours while all transgender experts agreed on suicidality and transphobia. Variables ranking is ongoing.
\
**Conclusion:** Though important topics, MSM health goes beyond HIV and STI, as our expert panel showed. Researchers should focus on the broader social context and mental health disparities while studying the health of this key population. Consulting with the local community, as we did in this paper, may help researchers to focus on the community’s priorities. The conditions selected in this Delphi will be explored in detail in a future qualitative study.
\ 