library(readr)
# Wave 1 data (open-ended questions coded in QualCoder3)
demog_data <- read_delim(here::here("data/demographic_data.csv"), 
                               delim = ";", 
                               escape_double = FALSE, 
                               col_types = cols(DEM02 = col_factor(levels = c("Cisgenre", 
                                                                              "Transgenre")), 
                                                DEM03 = col_factor(levels = c("18-29 ans",
                                                                              "30-39 ans", 
                                                                              "40-49 ans", 
                                                                              "50-59 ans",
                                                                              "60-69 ans")), 
                                                `ASS03[other]` = col_character(),
                                                ASS05 = col_number(), 
                                                ASS06 = col_factor(levels = c("Au moins une fois par mois",
                                                                              "Plusieurs fois par mois", 
                                                                              "Une fois par semaine ou plus",
                                                                              "Presque tous les jours"))), 
                               locale = locale(encoding = "ISO-8859-1"), 
                               trim_ws = TRUE)

codes_data <- read_csv(here::here("data/codes_cases_cat.csv"))

codes_data_fr <- read_csv(here::here("data/codes_cases_cat_fr.csv"),
                          locale = locale(encoding = "UTF-8"))

# Wave 2 data (likert-type questions directly from LimeSurvey)

.wave2_factors <-  c("Aucune importance",
                    "Peu important",
                    "Neutre",
                    "Important",
                    "Très important")

wave2_data <- read_delim(here::here("data/wave2.csv"),
                               delim = ",",
                               escape_double = FALSE,
                               col_types = cols(id = col_skip(),
                                                submitdate = col_skip(),
                                                lastpage = col_skip(),
                                                startlanguage = col_skip(),
                                                seed = col_skip(),
                                                token = col_skip(),
                                                `Q21C[SQ001]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ006]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ005]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ002]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ003]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ008]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ007]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ004]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ011]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ024]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ025]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ010]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ019]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ020]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ023]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ026]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ021]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ029]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ028]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ027]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ030]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ031]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ032]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ033]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ034]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ035]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ036]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ037]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ038]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ039]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ040]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ041]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ042]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ043]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ044]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ045]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ046]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ047]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ048]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ049]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ050]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ051]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ052]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ053]` = col_factor(levels = .wave2_factors),
                                                `Q21C[SQ054]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ001]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ006]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ005]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ002]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ003]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ008]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ007]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ004]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ011]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ024]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ025]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ010]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ019]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ020]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ023]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ026]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ021]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ029]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ028]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ027]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ030]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ031]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ032]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ033]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ034]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ035]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ036]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ037]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ038]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ039]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ040]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ041]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ042]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ043]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ044]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ045]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ048]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ050]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ054]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ055]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ056]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ057]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ058]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ059]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ060]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ061]` = col_factor(levels = .wave2_factors),
                                                `Q21T[SQ062]` = col_factor(levels = .wave2_factors)))